Help.map(Help.Type.MANUAL, "https://haml.info/docs/yardoc/file.REFERENCE.html")
Help.map(Help.Type.TUTORIAL, "https://haml.info/tutorial.html")
Help.map(Help.Type.CHEATSHEET, "https://devhints.io/haml")
Help.map(Help.Type.FAQ, "https://haml.info/docs/yardoc/file.FAQ.html")
Help.map(Help.Type.API, "https://haml.info/docs/yardoc/")
