#! /bin/bash

#------------------------------------------------------------------------------#
								  # Monitors #
#------------------------------------------------------------------------------#

# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor -d        

# xrandr_output=$(xrandr --current)
# monitors_count=$(echo "$xrandr_output" | grep "\sconnected" | wc -l)
main_monitor=$(monitors primary)
if [[ $(monitors count) -eq 1 ]]; then
	bspc monitor "$main_monitor" --rename main
	bspc monitor -d F W E R T A S D G C V
else
	bspc monitor "$main_monitor" --rename main
	bspc monitor main -d F W E R T A S D G

	i=0
	workspaces=(C V)
	# names=(left right)
	for m in $(monitors secondary); do
		# bspc monitor $m --rename ${names[i]}
		bspc monitor $m --reset-desktops ${workspaces[i]}
		((i = i + 1))
	done
fi

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

#------------------------------------------------------------------------------#
								  # Desktops #
#------------------------------------------------------------------------------#

bspc desktop W -l monocle
bspc desktop G -l monocle

#------------------------------------------------------------------------------#
								 # Distances #
#------------------------------------------------------------------------------#

bspc config border_width			1
bspc config borderless_monocle		true
bspc config focused_border_color	"$THEME_BLACK"
bspc config active_border_color		"$THEME_BG"
bspc config normal_border_color		"$THEME_BG"
bspc config window_gap				16
bspc config gapless_monocle			true
bspc config split_ratio				0.52

#------------------------------------------------------------------------------#
								   # Mouse #
#------------------------------------------------------------------------------#

# xsetroot -cursor_name left_ptr
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

#------------------------------------------------------------------------------#
								   # Rules #
#------------------------------------------------------------------------------#

set_rule() {
	state=$1 && shift
	for class in "$@"; do
		bspc rule -a "$class" state="$state"
	done
}

bspc rule -r "*"
bspc rule -a Screenkey manage=off
bspc rule -a scratchpad state=floating sticky=on rectangle=1200x800+220+260
bspc rule -a Gimp desktop=G follow=on
set_rule floating mpv Qalculate-gtk scummvm Pavucontrol Hdajackretask Arandr "Seafile Client"
# set_rule tiled Zathura Emacs
set_rule fullscreen Meld

#------------------------------------------------------------------------------#
								   # Panel #
#------------------------------------------------------------------------------#

polybarctl restart &

