#! /bin/sh

xsetroot -cursor_name left_ptr

#------------------------------------------------------------------------------#
								  # Monitors #
#------------------------------------------------------------------------------#

# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor -d        
xrandr_output=$(xrandr --current)
monitors_count=$(echo "$xrandr_output" | grep "\sconnected" | wc -l)
if [ $monitors_count -eq 1 ]; then
	main=$(echo "$xrandr_output" | grep "^eDP.*\sconnected" | cut -d" " -f1)
	bspc monitor $main --rename main
	bspc monitor -d F W E R T A S D G C V
else
	main=$(echo "$xrandr_output" | grep "^DP.*\sconnected" | cut -d" " -f1)
	bspc monitor $main --rename main
	bspc monitor main -d F W R A S D G C V

	left=$(echo "$xrandr_output" | grep "^HDMI.*\sconnected" | cut -d" " -f1)
	bspc monitor $left --rename left
	bspc monitor left -d E

	right=$(echo "$xrandr_output" | grep "^eDP.*\sconnected" | cut -d" " -f1)
	bspc monitor $right --rename right
	bspc monitor right -d T

fi

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

#------------------------------------------------------------------------------#
								  # Desktops #
#------------------------------------------------------------------------------#

bspc desktop W -l monocle
bspc desktop G -l monocle

#------------------------------------------------------------------------------#
								 # Distances #
#------------------------------------------------------------------------------#

# bspc config bottom_padding		0
bspc config border_width			1
bspc config borderless_monocle		true
# bspc config focused_border_color	$(xrdb-color blue)
# bspc config active_border_color		$(xrdb-color bg)
# bspc config normal_border_color		$(xrdb-color bg)
bspc config window_gap				16
bspc config gapless_monocle			true
bspc config split_ratio				0.52

#------------------------------------------------------------------------------#
								   # Mouse #
#------------------------------------------------------------------------------#

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

#------------------------------------------------------------------------------#
								   # Rules #
#------------------------------------------------------------------------------#

bspc rule -r "*"
bspc rule -a Meld state=fullscreen
bspc rule -a mpv state=floating
# bspc rule -a KeePassXC state=floating
bspc rule -a Screenkey manage=off
# bspc rule -a frontal state=floating rectangle=1200x800+360+200
bspc rule -a frontal state=floating rectangle=1200x800+260+220
bspc rule -a scratchpad state=floating sticky=on rectangle=1200x800+220+260
bspc rule -a Zathura state=tiled
bspc rule -a Qalculate-gtk state=floating
bspc rule -a scummvm state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Hdajackretask state=floating
bspc rule -a Emacs state=tiled

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Chromium desktop='^2'


#------------------------------------------------------------------------------#
								   # Panel #
#------------------------------------------------------------------------------#

# pgrep -x lemonbar.sh > /dev/null || lemonbar.sh &
~/.dotfiles/polybar/start.sh &

