#!/bin/sh

while read file
do
	case "$1" in
		"C-d")
			mv "$file" "$HOME/.local/share/Trash" ;;
		"C-r")
			convert -rotate 90 "$file" "$file" ;;
		"C-R")
			convert -rotate -90 "$file" "$file" ;;
		"C-c")
			echo -n "$file" | xclip -selection clipboard &&
			notify-send "$file copied to clipboard" & ;;
		w)
			wallpaper set "$file" ;;
		g)
			gimp "$file" & ;;
	esac
done

