#!/bin/sh

wallpaper_file="$HOME/.cache/wallpaper"

wallpaper() {
	# nitrogen --save --set-zoom-fill --head=$1 "$2"
	cp $file $wallpaper_file
	feh --no-fehbg --bg-fill $wallpaper_file
}

while read file
do
	case "$1" in
		"C-d")
			trash-put "$file" ;;
		"C-r")
			convert -rotate 90 "$file" "$file" ;;
		"C-R")
			convert -rotate -90 "$file" "$file" ;;
		"C-c")
			echo -n "$file" | xclip -selection clipboard &&
			notify-send "$file copied to clipboard" & ;;
		# "C-1")
		# 	wallpaper 0 "$file" ;;
		# "C-2")
		# 	wallpaper 1 "$file" ;;
		# "C-3")
		# 	wallpaper 2 "$file" ;;
		w)
			wallpaper "$file" ;;
		g)
			gimp "$file" & ;;
	esac
done

