#!/bin/sh

WM=bspwm

userresources=$DOTFILES/xorg/Xresources
sysresources=/etc/X11/xinit/.Xresources

[[ -f $sysresources ]] && xrdb -merge "$sysresources"
[[ -f $userresources ]] && xrdb -merge "$userresources"

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# [ -n $THEME ] && xrdb -merge $HOME/.dotfiles/themes/$THEME.xresources

source $DOTFILES/xorg/autostart.sh

{ [ $WM == bspwm ] && 
	sxhkd -c ~/.config/sxhkd/sxhkdrc ~/.config/bspwm/sxhkdrc ||
	sxhkd; } &

exec $WM > $XDG_STATE_HOME/$WM.log 2>&1

