#!/bin/sh

# Called by nsxiv(1) whenever an image gets loaded. The output is displayed in nsxiv's status bar.
# Arguments:
#   $1: path to image file
#   $2: image width
#   $3: image height

prefix=""
postfix=""
s=" | " # field separator

exec 2>/dev/null

filename=$(basename -- "$1")
filesize=$(du -Hh -- "$1" | cut -f 1)
geometry="${2}x${3}"
versions=$(find "${1%.*}".* -type f -maxdepth 0 | sed 's|.*\.||' | sort | tr '[:lower:]' '[:upper:]' | sed -E -e "s/JPE?G/ /" -e "s/DNG/ /" -e "s/SVG/縉/" -e "s/PNG/ /" -e "s/XMP/謹 /" | paste -sd " ")

echo "${prefix}${geometry}${s}${filesize}${s}${filename}${s}${versions}${postfix}"

